---
"$schema": http://json-schema.org/draft-04/hyper-schema
definitions:
  user:
    definitions:
      name:
        type:
        - string
        example: "r7kamura"
  gist:
    title: Gist
    description: Gist object
    type:
    - object
    required:
    - id
    definitions:
      id:
        description: Identifier of a gist
        type:
        - string
        example: "1"
      public:
        description: "Indicates whether the gist is public. Default: `false`"
        type:
        - boolean
        example: true
      description:
        description: the description for this gist
        type:
        - string
        example: "description of gist"
    links:
    - title: Show
      description: Get a single gist
      method: GET
      href: "/gists/{(#/definitions/gist/definitions/id)}"
      rel: show
    - title: List
      description: List the authenticated user's gists or if called anonymously, this will return all public gists
      method: GET
      href: "/gists"
      rel: instances
    - title: ListStarred
      description: List the authenticated user’s starred gists
      method: GET
      href: "/gists/starred"
      rel: instances
    - title: ListUsers
      description: List a user's gists
      href: "/users/{(#/definitions/user/definitions/name)}/gists"
      method: GET
      rel: instances
    - title: ListPublic
      description: List public gists
      href: "/gists/public"
      method: GET
      rel: instances
    - title: Create
      description: Create a gist
      href: "/gists"
      method: POST
      rel: create
      targetSchema:
        properties:
          description:
            "$ref": "#/definitions/gist/definitions/description"
          public:
            "$ref": "#/definitions/gist/definitions/public"
          files:
            description: A set of files whose key is a filename and the value is an object that has content key
            type:
            - object
    properties:
      id:
        "$ref": "#/definitions/gist/definitions/id"
properties:
  gist:
    "$ref": "#/definitions/gist"
type:
- object
description: GitHub API v3
links:
- href: https://api.github.com
  rel: self
title: GitHub API v3
